// <auto-generated />
using DataPublicApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataPublicApi.Migrations
{
    [DbContext(typeof(PublicApiContext))]
    [Migration("20230824095050_AddConstraintToPublicApiSettings")]
    partial class AddConstraintToPublicApiSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("user")
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataStore.PublicApiDb.Entities.PublicApiSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyRoundCount")
                        .HasColumnType("integer")
                        .HasColumnName("currency_round_count");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_currency");

                    b.HasKey("Id")
                        .HasName("pk_public_api_settings");

                    b.ToTable("public_api_settings", "user", t =>
                        {
                            t.HasCheckConstraint("rounding_cannot_be_less_than_zero", "currency_round_count >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
